lockdown: false
lockdown-reason: ""
    
max-warnings: 3
#3 days
warn-expirey-in-minutes: 4320 

color:
    primary: f
    secondary: a

chat-commands:
    - me
    - say

#Should we notify players with maxbans.notify whenever a banned player tries (fails) to join?
notify: true
#Should we verify names have the letters (A-Z,a-z,0-9 and _) only and are valid?
filter-names: true

#Should we use the DNS blacklist?
dnsbl:
    use: true
    servers:
    - bl.spamcop.net
    - sbl.spamhaus.org

database:
    mysql: false
    user: root
    pass: passwd
    host: localhost
    port: 3306
    name: maxbans