lockdown: false
lockdown-reason: ""

spawn:
    world: challenge_7
    x: 298.5
    y: 66
    z: -300.5
    
max-warnings: 3

color:
    primary: f
    secondary: a

chat-commands:
    - me
    - say