lockdown: false
lockdown-reason: ""
    
max-warnings: 3
#3 days
warn-expirey-in-minutes: 4320 

default-reason: "Misconduct"
appeal-message: ""

#The two char colors used that STAFF will see.
#Usually, primary = text, and secondary = variables (Like ban reason)
#0-9,a-f are valid. Also any Bukkit ChatColor is valid (Eg RED, AQUA, DARK_GRAY)
color:
    primary: f
    secondary: a
    
    
#This applies to kick, ban, and anything else.
kick-colors:
    #0-9,a-f are valid. Also any Bukkit ChatColor is valid (Eg RED, AQUA, DARK_GRAY)
    message: f #"You have been banned for:"
    reason: f #"Misconduct"
    regular: f #"By"
    banner: f #"Netherfoam"
    time: f #4 hours 59 minutes remaining.
    

chat-commands:
    - me
    - say

#Should we notify players with maxbans.notify whenever a banned player tries (fails) to join?
notify: true
#Should we verify names have the letters (A-Z,a-z,0-9 and _) only and are valid?
filter-names: true

#Should we use the DNS blacklist?
dnsbl:
    #Should we use this? Setting it to false disables DNSBL entirely.
    use: true
    #The DNSBL servers we should use to look up.  More servers = Slower results.
    #Each server takes approx 4 seconds to respond.  Use http://dnsbl.info to find
    #More servers, if you like.
    #DNSBL results are cached for 1 week, then expire (Are deleted).
    #This is how MaxBans checks for proxied IPs
    # 1.  Have we looked the IP up on DNSBL before, and has it not expired? If so go to 3
    # 2.  Start IP lookup, this takes a few seconds...
    # 3.  If the IP is not a proxy, stop checking, they're allowed, do not proceed to step 4.
    # 4.  Take appropriate action (Kick, notify) if any.
    servers:
    - bl.spamcop.net
    - sbl.spamhaus.org
    #Should we notify players with maxbans.notify when a player is joining with a proxy IP?
    notify: true
    #Should we kick players who are discovered to have proxy IPs?
    kick: false

database:
    mysql: false
    user: root
    pass: passwd
    host: localhost
    port: 3306
    name: maxbans