name: MaxBans
version: 1.3
main: org.maxgamer.maxbans.MaxBans
authors: [Darekfive, Netherfoam]

soft-depend: [HeroChat]

description: "A Rock Solid and Feather Light banning plugin!"
website: http://maxgamer.org

permissions:
    maxbans.ban:
        description: Allows a player to ban others.
        default: op
    maxbans.unban:
        description: Allows a player to unban others.
        default: op
    maxbans.tempban:
        description: Allows a player to tempban others.
        default: op
    maxbans.tempipban:
        description: Allows a player to temp IP ban others.
        default: op
    maxbans.ipban:
        description: Allows a player to IP ban others
        default: op
    maxbans.mute:
        description: Allows a player to mute/unmute others.
        default: op
    maxbans.unmute:
        description: Allows a player to unmute others.
        default: op
    maxbans.tempmute:
        description: Allows a player to temp mute others.
        default: op
    maxbans.checkban:
        description: Allows a player to check others ban info
        default: op
    maxbans.checkban.self:
        description: Allows a player to check their own ban info (and warnings)
        default: true
    maxbans.checkip:
        descriptions: Allows a player to lookup another players IP address
        default: op
    maxbans.dupeip:
        description: Allows a player to check other accounts that use the same IP address as the given one
        default: op
    maxbans.warn:
        description: Allows a player to give out warnings to others.
        default: op
    maxbans.clearwarnings:
        description: Allows a player to delete all warnings for a given player.
        default: op
    maxbans.kick:
        description: Allows a player to kick others with a reason
        default: op
    maxbans.lockdown.use:
        description: Allows a player to use /lockdown on|off.
        default: op
    maxbans.lockdown.bypass:
        description: Allows a player to enter the server if lockdown is enabled
        default: op
    maxbans.history:
        description: Allows the player to use /history to view recent maxbans changes
        default: op
    maxbans.forcespawn:
        description: Allows a player to use /forcespawn on another player. This teleports them to the spawn.
        default: op
    maxbans.reload:
        description: Allows a player to use /mbreload, reloading MaxBans from scratch.
        default: op
    maxbans.import:
        description: Allows a player to use /mbimport, importing bans.
        default: op
    maxbans.export:
        description: Allows a player to use /mbexport, exporting bans.
        default: op
    maxbans.seesilent:
        description: Allows a player to see other players using silent ban commands
        default: op
    maxbans.seebroadcast:
        description: Allows a player to see other players using regular ban commands (Not silent ones)
        default: true

commands:
    ban:
        description: Bans a player
        usage: /ban <player> [-s] <reason>
        aliases: [mbban]
    unban:
        description: Unbans a player, includes ip bans
        usage: /unban <player>
        aliases: [mbunban]
    tempban:
        description: Bans a player temporarily
        usage: /tempban <player> <time> <timeform> [-s] <reason>
        aliases: [mbtempban]
    tempipban:
        description: Temporarily ip bans a player
        usage: /tempipban <player> <time> <timeform> [-s] <reason>
        aliases: [mbtempipban]
    ipban:
        description: IP bans a player
        usage: /ipban <player> [-s] <reason>
        aliases: [mbipban]
    mute:
        description: Toggles a players mute
        usage: /mute <player>
        aliases: [mbmute]
    unmute:
        description: Unmutes a player
        usage: /unmute <player>
        aliases: [mbunmute]
    tempmute:
        description: Mutes a player for a time
        usage: /tempmute <player> <time> <timeform>
        aliases: [mbtempmute]
    checkban:
        description: Reports any mutes, bans or ipbans a player has
        usage: /checkban <player>
        aliases: [mbcheckban]
    checkip:
        description: Reports a players IP address
        usage: /checkip <player>
        aliases: [mbcheckip]
    dupeip:
        description: Scans a players IP address and reports anyone else who uses it.
        usage: /dupeip <player>
        aliases: [mbdupeip]
    warn:
        description: Warns a player
        usage: /warn <player> <reason>
        aliases: [mbwarn]
    clearwarnings:
        description: Removes a players warning history
        usage: /clearwarnings <player>
        aliases: [mbclearwarnings]
    kick:
        description: Kicks a player from the game
        usage: /kick <player> [reason]
        aliases: [mbkick]
    lockdown:
        description: Prevents anyone without maxbans.lockdown.bypass from joining. Toggles if no reason given.
        usage: /lockdown [reason]
        aliases: [mblockdown]
    history:
        description: Reports recent usage of MaxBans.
        usage: /history <number>
        aliases: [mbhistory]
    forcespawn:
        description: Teleports a player to the spawn.
        usage: /forcespawn <player>
        aliases: [mbforcespawn]
    mbreload:
        description: Reloads MaxBans from the DB and config
        usage: /mbreload
    mb:
        description: Displays MaxBans commands that you have access to
        usage: /mb
        aliases: [maxbans]
    mbimport:
        description: Imports a set of bans
        usage: /mbimport nameOfPlugin
    mbexport:
        description: Exports a set of bans
        usage: /mbexport nameOfPlugin
    mbdebug:
        description: Print debug info to the console
        usage: /mbdebug